name: action
description: Perform action

runs:
  using: "composite"
  env:
    GITHUB_TOKEN: ${{ github.token }}
  steps:
    - id: go
      run: |
        echo "${#GITHUB_TOKEN}"
        pwd
      shell: bash
