name: action
description: Perform action

inputs:
  repository:
    description: 'Repository'
    default: ${{ github.action_repository }}

runs:
  using: "composite"
  steps:
    - run: |
        echo "$INPUT_REPOSITORY"
        echo "PWD"
      shell: bash
