name: action
description: Perform action

inputs:
  repository:
    description: 'Repository'
    default: ${{ github.repository }}
  action_repository:
    description: 'Action Repository'
    default: ${{ github.action_repository }}

runs:
  using: "composite"
  steps:
    - run: |
        pwd
      shell: bash
      working-directory: ${{ github.action_path }}
