name: action
description: Perform action

inputs:
  action_path:
    description: 'Action Path'
    default: ${{ github.action_path }}

runs:
  using: "composite"
  steps:
    - run: echo "${{ inputs.action_path }}"
      shell: bash
    - run: echo "${{ github.action_path }}"
      shell: bash
