name: "Test"
description: "Test"
runs:
  using: "composite"
  steps:
    - id: github
      uses: pl-strflt/docker-container-action/.github/actions/github@v1
    - run: echo $GITHUB_ACTION_PATH
    - run: git show
      workdir: ${{ env.GITHUB_ACTION_PATH }}
