name: "Test"
description: "Test"
runs:
  using: "composite"
  steps:
    - id: github
      uses: pl-strflt/docker-container-action/.github/actions/github@v1
    - run: echo $GITHUB_ACTION_PATH
      shell: bash
    - run: ls -a
      shell: bash
      working-directory: /home/runner/work/_actions
