name: Add Issues to GUI project

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Wether to perform a dry run
        required: false
        default: 'true'
      query:
        description: Query multiplier to use when looking for issues
        required: false
        default: ''

#  schedule:
#    # “At minute 25 past every 12th hour.” - https://crontab.guru/#25_*/12_*_*_*
#    - cron:  '25 */12 * * *'


jobs:
  add:
    name: Add Issues to GUI project
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GALARGH_GITHUB_TOKEN }}
    steps:
      - id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: actions/checkout@v3
      - run: npm install && npm run build
        working-directory: scripts
      - run: |
          node lib/actions/add-issues-to-gui-project.js \
            --dryRun ${{ github.event.inputs.dry-run || 'false' }} \
            --query ${{ github.event.inputs.query || format('created:{0}', steps.date.outputs.date) }}
        working-directory: scripts
