name: Playground

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    paths: ['.github/workflows/playground.yml', '**/*.yml']
  release:
    types:
      - published
      - released

permissions:
  checks: write

defaults:
  run:
    shell: bash

env:
  ABC: 123

jobs:
  playground:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World!"
      
  playground2:
    needs: playground
    if: ${{ !cancelled() && true || needs.playground.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World!"
