on:
  workflow_run:
    workflows: 
      - Playground
    types:
      - completed

jobs:
  playground2:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.event == 'pull_request' &&
        github.event.workflow_run.conclusion == 'success'
    strategy:
      fail-fast: false
      matrix:
        include: ${{ github.event.workflow_run.pull_requests }}
    steps:
      - run: echo "${{ toJSON(github.event) }}"
        shell: bash
