on:
  workflow_run:
    workflows: 
      - Playground
    types:
      - completed

jobs:
  playground2:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        number: ${{ github.event.workflow_run.pull_requests.*.number }}
    steps:
      - run: echo "${{ matrix.number }}"
