on:
  merge_group:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
  workflow_run:
    workflows: 
      - Playground
    types:
      - completed

jobs:
  playground2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJSON(github.event) }}"
