name: Playground 2

on:
  push:
    tags:
      - v0.0.0

defaults:
  run:
    shell: bash

jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
    - run: echo "$GITHUB_EVENT"
      env:
        GITHUB_EVENT: ${{ github.event }}
