name: Playground

on:
  workflow_dispatch:
    inputs:
      workflow_group:
        type: string
        description: Workflow concurrency group
        default: workflow
      workflow_cancel_in_progress:
        type: boolean
        description: Workflow concurrency cancel in progress
        default: false
      job_group:
        type: string
        description: Job concurrency group
        default: job
      job_cancel_in_progress:
        type: boolean
        description: Job cancel in progress
        default: false
      secret:
        type: string
        description: Secret
        default: 123
  workflow_call:
  pull_request:
  push:
    paths: ['.github/workflows/playground.yml', '**/*.yml']
  release:
    types:
      - published
      - released

permissions:
  checks: write

defaults:
  run:
    shell: bash

env:
  ABC: 123

concurrency:
  group: ${{ github.event.inputs.workflow_group }}
  cancel-in-progress: ${{ github.event.inputs.workflow_cancel_in_progress }}

jobs:
  playground:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.event.inputs.job_group }}
      cancel-in-progress: ${{ github.event.inputs.cancel_in_progress }}
    steps:
      - run: echo "${{ github.event.inputs.secret }}"
      - run: sleep 60
      - run: echo "${{ github.event.inputs.secret }}"
  playground2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.inputs.secret }}"
      
