name: Playground 2

on:
  workflow_call:
    inputs:
      abc:
        type: string
        required: false
        description: ABC
        default: ${{ vars.ABC }}

defaults:
  run:
    shell: bash

jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
    - run: echo "$GITHUB_EVENT"
      env:
        GITHUB_EVENT: ${{ github.event.inputs.abc }}
