name: Playground 2

on:
  workflow_run:
    workflows: ["Playground"]
    types:
      - completed

defaults:
  run:
    shell: bash

jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
    - id: event
      uses: galargh/.github/.github/actions/action@master
      with:
        artifact-names: ten,eleven
    - env:
        JOBS: ${{ steps.event.outputs.jobs }}
        LOGS: ${{ steps.event.outputs.logs }}
        ARTIFACTS: ${{ steps.event.outputs.artifacts }}
      run: echo Goodbye
