name: Playground 2

on:
  push:
    tags:
      - '*'

defaults:
  run:
    shell: bash

jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
    - run: echo "$GITHUB_EVENT"
      env:
        GITHUB_EVENT: ${{ toJSON(github.event) }}
