on:
  workflow_call:
    inputs:
      secret:
        default: Hello
        type: string
        required: false
      secret2:
        default: ${{ secrets.GALARGH_GITHUB_TOKEN }}
        type: string
        required: false

jobs:
  playground2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJSON(inputs) }}"
        shell: bash
