name: Playground

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      count:
        type: number
        default: 0
  pull_request:
  push:
    paths: ['.github/workflows/playground.yml', '**/*.yml']
  release:
    types:
      - published
      - released

permissions:
  checks: write

defaults:
  run:
    shell: bash

env:
  ABC: 123

jobs:
  playground:
    uses: ./.github/workflows/playground2.yml
