name: Release
on:
  push:
    paths: [CHANGELOG.md]
    branches: [master, release]
  pull_request:
    paths: [CHANGELOG.md]
    branches: [master, release]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: pl-strflt/changelog-driven-release@fix-draft-release-target
        with:
          path: CHANGELOG.md
          draft: ${{ github.event_name == 'pull_request' }}
