name: Sync

on:
  workflow_dispatch:
    inputs:

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GALARGH_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: protocol/github-mgmt-router
          ref: sync
      - run: npm ci
      - run: npm run sync
